### ISSUE TITLE
Add Http Forwarder

### ISSUE THREAD

**Issue by FuncGuy** [bangunindo/trap2json#7]
trap2json supports Kafka integration and others except HTTP Is it possible to add HTTP forwarder

**Comment by iqbalaydrus** [comment]
Our first request on our first open source project!

Yes it is possible and I think it's trivial to implement. We still don't know when to add http support, since internally we don't use it. However, feel free to submit PR!

**Comment by iqbalaydrus** [comment]
Well since I had free time, I implemented what you asked. It should be available soon in v0.5.0. Let me know what you think!
